### ISSUE TITLE
v6.0.0 Release

### ISSUE THREAD

**Issue by bighappyface** [jsonrainbow/json-schema#527]
I am opening an issue for the v6.0.0 release to help focus the discussion.

I have updated the [v6.0.0 project](https://github.com/justinrainbow/json-schema/projects/2) to match the outline from @erayd in https://github.com/justinrainbow/json-schema/pull/390#issuecomment-301631526.

**Comment by oligriffiths** [comment]
Hey folks.
Just wondering how the 6.0.0 release is going? I notice that the code in master does not match what is installed with `composer install` right now, which is a bit confusing.

**Comment by anvyst** [comment]
@bighappyface @erayd hey, guys. Is there any chance of helping out testing currently pending pull requests and helping in v6.0.0 roadmap progress?

**Comment by erayd** [comment]
@anvyst Any help you can provide on this project is useful, and would be very welcome. There are very few people actively involved, and none of us have much available time.

Is there something in particular you'd like to focus on?

**Comment by anvyst** [comment]
@erayd, we're heavily using your package in `QoboLtd/project-template-cakephp` repository. 
As a start, we've found a minor bug that we tried resolving in #553 , that's still pending in PR reviewal stage. 

In general, we could go through some of the pull requests, that been hanging there for quiet some time.

**Comment by erayd** [comment]
@anvyst I lost sight of that one sorry - I will commit to having it reviewed before the end of next week, and hopefully merged. If you haven't seen progress on it by Wednesday, please feel free to remind me again.

As far as other PRs etc. go, are there any particular ones which are annoying you?

**Comment by scottux** [comment]
Almost a year later now, how is this release coming along?

**Comment by erayd** [comment]
@scottux Incredibly slowly. This is a free-time project with *very* little in the way of manpower.

If you're offering to help, your contribution would be welcome.

**Comment by dafeder** [comment]
@erayd how can people figure out how/where to plug in to help move this forward? Is the [project](https://github.com/justinrainbow/json-schema/projects/2) the source of truth?

**Comment by DannyvdSluijs** [comment]
Discussions about getting the version 6.0.0 release is taking place in #721, I'll close this issue for now in order to focus the attention there.
