### ISSUE TITLE
Relative paths resolving to unit test, not the schema

### ISSUE THREAD

**Issue by tekmosis** [jsonrainbow/json-schema#557]
When using Laravel's packages we have JSON Schemas in multiple directories. Each one can be referenced and we're hoping to use it with relative paths. This works fine in Laravel with the validation on form request, it uses the relative path to the .schema.json

However with this package the relative path is of the unit test.

**Comment by erayd** [comment]
Could you provide a concise example please?

Relative paths should resolve relative to their parents schema. If there is no parent schema, then a relative path isn't valid - you must supply an absolute one.

**Comment by uncaught** [comment]
Yes, there is a bug in the `UriResolver::combineRelativePathWithBasePath` - I've written a test:

```php
use JsonSchema\Uri\UriResolver;
use PHPUnit\Framework\Constraint\IsEqual;
use PHPUnit\Framework\TestCase;

class UriResolverTest extends TestCase {

  public function testcombineRelativePathWithBasePath(): void {
    $base = '/var/packages/flow-api/tests/UnitTests/DemoData/../../../schema/Customer/CustomerSchema_latest.json';
    $relative = '../../../schema/UuidSchema.json';
    $combined = UriResolver::combineRelativePathWithBasePath($relative, $base);
    $expectedPath =
      '/var/packages/flow-api/tests/UnitTests/DemoData/../../../schema/Customer/../../../schema/UuidSchema.json';
    $expectedRealPath = realpath($expectedPath);
    self::assertThat(
      $combined,
      self::logicalOr(
        new IsEqual($expectedPath),
        new IsEqual($expectedRealPath)
      )
    );
  }
}
```
> Failed asserting that '/var/packages/flow-api/tests/UnitTests/DemoData/../../schema/UuidSchema.json' is equal to '/var/packages/flow-api/tests/UnitTests/DemoData/../../../schema/Customer/../../../schema/UuidSchema.json' or is equal to '/var/packages/schema/UuidSchema.json'.

I've yet to understand, why the Method `combineRelativePathWithBasePath` is so complicated. Can't you simply use a `dirname($basePath) . "/$relativePath"` ?

**Comment by uncaught** [comment]
We've been using my fork in production for nearly 2 years now. This is a bug and without the fix our tests fail.

The `dirname` is just a string operation, it is not limited to file paths and also works for URLs. It doesn't work on the file system.
