### ISSUE TITLE
Triage on Issues & Pull requests

### ISSUE THREAD

**Issue by DannyvdSluijs** [jsonrainbow/json-schema#716]
# Introduction
As mentioned in https://github.com/justinrainbow/json-schema/issues/658#issuecomment-1926950044 I was going to do some triage on the issues and pull requests. Since early february I've been going through the majority of them and have a pretty good overview of what can be done. And some reporters even stepped up and updated their issue/PR or closed them.
This list below includes all open issues at least and some of the pull requests. Given the amount of actionable items already I didn't feel right to also include all pull request at this point as well.

Below you can find groups and suggested actions which should help with cleaning up the repo and get back to a manageable state. Since I don't have any permissions on this report this issue needs the help of @erayd or other maintainers (or my permissions should be elevated to do so.) Withing the groups the issues/pull request have been ordered from oldest to newest.

# Issues from Ghost users
These issue once have been reported but the user account since the report has been deleted so there won't be any feedback from the original reports ever. I would suggest closing these issues.
- https://github.com/justinrainbow/json-schema/issues/519
- https://github.com/justinrainbow/json-schema/issues/554
- https://github.com/justinrainbow/json-schema/issues/571

# Issues & Pull requests that can be closed
These issues have either been answered, chased after or are clearly outdated. My advice would be to close these with a friendly message indicating that if people believe this was incorrectly closed reopening them is a valid option
- https://github.com/justinrainbow/json-schema/issues/279
- https://github.com/justinrainbow/json-schema/issues/311
- https://github.com/justinrainbow/json-schema/issues/324
- https://github.com/justinrainbow/json-schema/issues/343
- https://github.com/justinrainbow/json-schema/issues/352
- https://github.com/justinrainbow/json-schema/issues/445
- https://github.com/justinrainbow/json-schema/issues/467
- https://github.com/justinrainbow/json-schema/issues/493
- https://github.com/justinrainbow/json-schema/issues/499
- https://github.com/justinrainbow/json-schema/issues/503
- https://github.com/justinrainbow/json-schema/issues/517
- https://github.com/justinrainbow/json-schema/issues/525
- https://github.com/justinrainbow/json-schema/issues/530
- https://github.com/justinrainbow/json-schema/issues/531
- https://github.com/justinrainbow/json-schema/issues/538
- https://github.com/justinrainbow/json-schema/issues/551
- https://github.com/justinrainbow/json-schema/issues/561
- https://github.com/justinrainbow/json-schema/pull/565
- https://github.com/justinrainbow/json-schema/issues/570
- https://github.com/justinrainbow/json-schema/issues/576
- https://github.com/justinrainbow/json-schema/issues/586
- https://github.com/justinrainbow/json-schema/issues/627
- https://github.com/justinrainbow/json-schema/issues/628
- https://github.com/justinrainbow/json-schema/issues/647
- https://github.com/justinrainbow/json-schema/issues/674
- https://github.com/justinrainbow/json-schema/issues/677
- https://github.com/justinrainbow/json-schema/issues/679

# Issues & Pull requests that should be kept
These issues seem valid and are worth spending time on with the goal of making a improvement to the library. Behind the issues you can find one or more suggested labels in order to make its state clear to all readers.
- https://github.com/justinrainbow/json-schema/issues/258 **labels:** Windows support & Bug
- https://github.com/justinrainbow/json-schema/issues/333 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/391 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/501 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/508 **labels:** Accepting PR & Bug
- https://github.com/justinrainbow/json-schema/issues/526 **labels:** Accepting PR & Bug
- https://github.com/justinrainbow/json-schema/issues/557**labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/578 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/579 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/622 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/645 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/pull/682 **labels:** Adjustment needed
- https://github.com/justinrainbow/json-schema/issues/685 **labels:** Accepting PR

# Issues & Pull requests closed due to chasing reporters
I've been actively asking for feedback on issues and pull requests and some reporters have been so kind to close their issues something even with proper feedback. No action is required, just wanted to list them here in order to have a complete overview.
- https://github.com/justinrainbow/json-schema/issues/239
- https://github.com/justinrainbow/json-schema/issues/266
- https://github.com/justinrainbow/json-schema/issues/340
- https://github.com/justinrainbow/json-schema/issues/348
- https://github.com/justinrainbow/json-schema/issues/504
- https://github.com/justinrainbow/json-schema/issues/514
- https://github.com/justinrainbow/json-schema/issues/522
- https://github.com/justinrainbow/json-schema/issues/524
- https://github.com/justinrainbow/json-schema/issues/534
- https://github.com/justinrainbow/json-schema/issues/539
- https://github.com/justinrainbow/json-schema/issues/540
- https://github.com/justinrainbow/json-schema/issues/569
- https://github.com/justinrainbow/json-schema/pull/581
- https://github.com/justinrainbow/json-schema/pull/582
- https://github.com/justinrainbow/json-schema/issues/588
- https://github.com/justinrainbow/json-schema/issues/623
- https://github.com/justinrainbow/json-schema/pull/641
- https://github.com/justinrainbow/json-schema/pull/659
- https://github.com/justinrainbow/json-schema/pull/660
- https://github.com/justinrainbow/json-schema/pull/661
- https://github.com/justinrainbow/json-schema/issues/680
- https://github.com/justinrainbow/json-schema/issues/699
- https://github.com/justinrainbow/json-schema/issues/713

# Issues that need a more in depth triage
These issues seem more complex and/or have an extensive comment history which makes it challanging to do a basic triage and make a advise on what to do with them. For now I would keep them and in due time take them one at a time and deep dive into the issue and determine what to do.
- https://github.com/justinrainbow/json-schema/issues/396
- https://github.com/justinrainbow/json-schema/issues/407
- https://github.com/justinrainbow/json-schema/issues/408
- https://github.com/justinrainbow/json-schema/issues/417
- https://github.com/justinrainbow/json-schema/issues/444
- https://github.com/justinrainbow/json-schema/issues/497
- https://github.com/justinrainbow/json-schema/issues/503
- https://github.com/justinrainbow/json-schema/issues/510
- https://github.com/justinrainbow/json-schema/issues/523
- https://github.com/justinrainbow/json-schema/issues/527
- https://github.com/justinrainbow/json-schema/issues/541
- https://github.com/justinrainbow/json-schema/issues/552
- https://github.com/justinrainbow/json-schema/issues/632
- https://github.com/justinrainbow/json-schema/issues/711
- https://github.com/justinrainbow/json-schema/issues/712

# Issues reported by @erayd
These are reported by the most active maintainer and are seemingly very valuable. These should also be labelled accordingly. 
- https://github.com/justinrainbow/json-schema/issues/374 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/392 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/395  **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/426 **labels:** Accepting PR
- https://github.com/justinrainbow/json-schema/issues/598 **labels:** Accepting PR

These should be closed in my opinion, see those tickets for my reasoning
- https://github.com/justinrainbow/json-schema/issues/426
- https://github.com/justinrainbow/json-schema/issues/438

**Comment by erayd** [comment]
Thank you very, very much for doing this work @DannyvdSluijs - really appreciate it! I am hoping to find some time this weekend to start acting on this list.

**Comment by DannyvdSluijs** [comment]
Closing this issue for now. I've become a maintainer and actively working on ploughing through the issue and pull request lists. Version `6.0.0` has been released
