### ISSUE TITLE
List on json-schema.org

### ISSUE THREAD

**Issue by benjagm** [jsonrainbow/json-schema#750]
Hello! My name is Benjamin from the JSON Schema Community. I came across this cool JSON Schema implementation, and I wanted to congratulate you for the great work! KUDOS!

I noticed that it's not listed on our [tooling page](https://json-schema.org/tools), but we'd love it to be.
If you'd like to add this implementation to that page, please feel free to open an issue to get it added using this [link](https://github.com/json-schema-org/website/issues/new?assignees=&labels=Status%3A+Triage&template=adding-your-tooling.yml).

I'd like to use this opportunity to invite you to join the [JSON Schema Community in Slack](https://json-schema.org/slack), where we have some interesting channels like #implementers where you could connect with other relevant maintainers in the ecosystem.

Thanks for enhancing the JSON Schema ecosystem!

**Comment by DannyvdSluijs** [comment]
I've also listed the Slack community link in our [wiki](https://github.com/jsonrainbow/json-schema/wiki).
Closing this issue for now. Thanks again, for reaching out @benjagm
