### ISSUE TITLE
Trouble with maxProperties on array type

### ISSUE THREAD

**Issue by mrFANRA** [jsonrainbow/json-schema#762]
Hi! Here is something stranger. 

```
$value  =   [
    "id" => 111,
];

$validator = new Validator();
$validator->validate($value,[
    "type"  =>  "array",
    "properties"    => [
        "id"=>[
            "type"  =>  "number",
        ],
        "at"=>[
            "type"  =>  "string",
        ],
    ],
    "maxProperties"=> 1,
    "minProperties"=> 1,
]);

// error message:  Must contain a minimum of 1 properties
```

But in this way all is fine:
```
$value  =   json_decode(json_encode([
    "id" => 111,
]));

$validator = new Validator();
$validator->validate($value,[
    "type"  =>  "object",
    "properties"    => [
        "id"=>[
            "type"  =>  "number",
        ],
        "at"=>[
            "type"  =>  "string",
        ],
    ],
    "maxProperties"=> 1,
    "minProperties"=> 1,
]);

//  Success
```

**Comment by DannyvdSluijs** [comment]
Hi @mrFANRA 

At first glance I can see a potential issue with
```php
$value  =   [
    "id" => 111,
];
```

This isn't a structure (associative array) which cannot be expressed in JSON. In the second example the side effect of the JSON encode/decode is that your `$value` is of the type `\stdClass` which is on object and not an array.

**Comment by DannyvdSluijs** [comment]
Hi @mrFANRA 

It seems your schema is perhaps maybe not what you think it is, as you are combining `"type": "array"` with the `properties` keyword. When `type` is an an array you need to specify what you expect inside the array using the `items` keyword.

So if you wish to validate it to be an array of objects which have either the `id` or `at` property you would need a schema as such:
```php
$value  =   [
    (object) ["id" => 111],
];

$validator = new Validator();
$result = $validator->validate($value,[
    "type"  =>  "array",
    "items" => [
        "type" => "object",
        "properties"    => [
            "id"=>[
                "type"  =>  "number",
            ],
            "at"=>[
                "type"  =>  "string",
            ],
        ],
        "maxProperties"=> 1,
        "minProperties"=> 1,
    ]
]);

// Success
var_dump($result, $validator->getErrors());
```

Mind the out type `array` with the `items` keyword defining an inner type `object` with the properties and the min/max constraints. Secondly also look at `$value` which is now an array with an object (`\stdClass'`)

And to re-iterate only PHP natively support associative arrays. Other programming languages have alternatives but no native support. This is why we cast `["id" => 111]` to an object.

Hope this helps, if you think there is still an issue with the library we would love to hear back from you.

**Comment by mrFANRA** [comment]
Ok. Thanks Im understand!
